"""initial handbook table

Revision ID: a8627e21c75c
Revises: ea4260c877c2
Create Date: 2026-04-05 18:48:03.282765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a8627e21c75c'
down_revision: Union[str, None] = 'ea4260c877c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_handbook_location'), table_name='handbook')
    op.drop_constraint(op.f('uq_handbook_year_course_location'), 'handbook', type_='unique')
    op.create_unique_constraint('uq_handbook_year_course', 'handbook', ['year', 'course'])
    op.drop_column('handbook', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('handbook', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint('uq_handbook_year_course', 'handbook', type_='unique')
    op.create_unique_constraint(op.f('uq_handbook_year_course_location'), 'handbook', ['year', 'course', 'location'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_handbook_location'), 'handbook', ['location'], unique=False)
    # ### end Alembic commands ###
