"""initial handbook table

Revision ID: ea4260c877c2
Revises: 
Create Date: 2026-04-05 13:55:37.483669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ea4260c877c2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handbook',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('information', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'course', 'location', name='uq_handbook_year_course_location')
    )
    op.create_index(op.f('ix_handbook_course'), 'handbook', ['course'], unique=False)
    op.create_index(op.f('ix_handbook_location'), 'handbook', ['location'], unique=False)
    op.create_index(op.f('ix_handbook_year'), 'handbook', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_handbook_year'), table_name='handbook')
    op.drop_index(op.f('ix_handbook_location'), table_name='handbook')
    op.drop_index(op.f('ix_handbook_course'), table_name='handbook')
    op.drop_table('handbook')
    # ### end Alembic commands ###
